version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      app-dependencies:
        dependency-type: production
      dev-tooling:
        dependency-type: development
